# Семинар 1

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

Число осей:

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [9]:
np.sum(vec)

21

In [10]:
np.sum(vec, axis=0)

array([ 9, 12])

In [11]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [12]:
vec.sum()

21

Транспонируем массив:

In [13]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [15]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [16]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [19]:
vec[:, 1]

array([2, 4, 6])

In [20]:
vec[2, :]

array([5, 6])

In [21]:
vec[1:2, 0]

array([3])

In [22]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [23]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [25]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [27]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [29]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [30]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [31]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [32]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [33]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [34]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [35]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [41]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [45]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [46]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [42]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [44]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [47]:
np.random.rand(2, 3)

array([[0.8216102 , 0.76755896, 0.31812921],
       [0.92759537, 0.53224039, 0.74105082]])

In [48]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [49]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [50]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [51]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [52]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [53]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 26.2 s, sys: 65.7 ms, total: 26.2 s
Wall time: 26.6 s


In [54]:
%%time
C = A @ B

CPU times: user 3.88 ms, sys: 3.02 ms, total: 6.9 ms
Wall time: 8.21 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [57]:
# ┌(▼▼メ)┘ └(メ▼▼)┐
import numpy as np

# 1. Одномірний масив
def reverse_array(arr):
    return np.flip(arr)

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = reverse_array(arr)
print("1. Масив:", reversed_arr)

1. Массив: [5 4 3 2 1]


In [58]:
# 2. Знайти максимальний непарний елемент в масиві
def max_odd_element(arr):
    odd_elements = arr[arr % 2 != 0]
    if len(odd_elements) == 0:
        return None
    return np.max(odd_elements)

max_odd = max_odd_element(arr)
print("2. Максимальний непарний елемент:", max_odd)

2. Максимальний непарний елемент: 5


In [59]:
# 3. Замініть усі непарні елементи масиву на ваше улюблене число
def replace_odd_elements(arr, favorite_number):
    arr[arr % 2 != 0] = favorite_number
    return arr

favorite_number = 7
arr = np.array([1, 2, 3, 4, 5])
modified_arr = replace_odd_elements(arr, favorite_number)
print("3. Масив із заміненими непарними елементами:", modified_arr)

3. Масив із заміненими непарними елементами: [7 2 7 4 7]


In [61]:
# 4. Створіть масив перших n непарних чисел, записаних у порядку спадання
def first_n_odd_numbers_descending(n):
    return np.arange(2*n-1, 0, -2)
n = 5
odd_numbers_descending = first_n_odd_numbers_descending(n)
print("4. Масив перших", n, "непарних чисел у порядку спадання:", odd_numbers_descending)

4. Масив перших 5 непарних чисел у порядку спадання: [9 7 5 3 1]


In [62]:
# 5. Обчисліть найближче і найдальше числа до даного в розглянутому масиві чисел
def closest_and_farthest_numbers(arr, number):
    closest_index = np.abs(arr - number).argmin()
    farthest_index = np.abs(arr - number).argmax()
    return arr[closest_index], arr[farthest_index]

arr = np.array([0, 1, 2, 3, 4])
number = 1.33
closest, farthest = closest_and_farthest_numbers(arr, number)
print("5. Найближче число:", closest)
print("   Найближче число:", farthest)

5. Найближче число: 1
   Найближче число: 4


In [63]:
# 6. Обчислювальну первісну заданого полінома
def antiderivative(coefficients, constant):
    n = len(coefficients)
    antiderivative_coeffs = [coefficients[i] / (n-i) for i in range(n)]
    antiderivative_coeffs.append(constant)
    return np.array(antiderivative_coeffs)

coefficients = np.array([4, 6, 0, 1])
constant = 3
antiderivative_coeffs = antiderivative(coefficients, constant)
print("6. Коефіцієнти первісної:", antiderivative_coeffs)

6. Коефіцієнти первісної: [1. 2. 0. 1. 3.]


In [64]:
# 7. Користуючись пунктом 6, порахуйте першу похідну для заданого полінома у заданій точці
def derivative_at_point(coefficients, point):
    antiderivative_coeffs = antiderivative(coefficients, 0)
    derivative_coeffs = np.polyder(antiderivative_coeffs)
    return np.polyval(derivative_coeffs, point)

point = 2
derivative = derivative_at_point(coefficients, point)
print("7. перша похідна у точці", point, ":", derivative)

7. перша похідна у точці 2 : 57.0
